language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - REQ="Django>=1.7,<1.8 django-mptt<0.8"
  - REQ="Django>=1.8,<1.9 django-mptt<0.8"
  - REQ="Django>=1.9,<1.10 django-mptt"
  - REQ="Django>=1.10,<1.11 django-mptt-nomagic"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U pip wheel setuptools
  - pip install $REQ Pillow flake8 pytz
  - python setup.py install
# command to run tests, e.g. python setup.py test
script: "cd tests && ./manage.py test testapp && flake8 ."
