language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO_REQUIREMENT="Django>=1.4,<1.5"
  - DJANGO_REQUIREMENT="Django>=1.5,<1.6"
  - DJANGO_REQUIREMENT="Django>=1.6,<1.7"
  - DJANGO_REQUIREMENT="Django>=1.7,<1.8"
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_REQUIREMENT="Django>=1.7<1.8"
    - python: "3.2"
      env: DJANGO_REQUIREMENT="Django>=1.4,<1.5"
    - python: "3.3"
      env: DJANGO_REQUIREMENT="Django>=1.4,<1.5"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q $DJANGO_REQUIREMENT django-mptt Pillow feedparser flake8 --use-mirrors
  - python setup.py -q install
# command to run tests, e.g. python setup.py test
script: "cd tests && ./manage.py test testapp && flake8 ."
