language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - REQ="Django>=1.7,<1.8 django-mptt<0.8"
  - REQ="Django>=1.8,<1.9 django-mptt<0.8"
  - REQ="Django>=1.9,<1.10 django-mptt"
  - REQ="Django>=1.10,<1.11 django-mptt"
  - REQ="Django>=1.11,<2.0 django-mptt"
  - REQ="https://github.com/django/django/archive/master.zip django-mptt"
matrix:
  exclude:
    - python: "3.5"
      env: REQ="Django>=1.7,<1.8 django-mptt<0.8"
    - python: "2.7"
      env: REQ="https://github.com/django/django/archive/master.zip django-mptt"
  allow_failures:
    - env: REQ="https://github.com/django/django/archive/master.zip django-mptt"
install:
  - pip install -U pip wheel setuptools
  - pip install $REQ Pillow flake8 pytz
  - python setup.py install
script: "cd tests && ./manage.py test testapp && cd .. && flake8 ."
